Update mgm.yml

diff --git a/.github/workflows/mgm.yml b/.github/workflows/mgm.yml
--- a/.github/workflows/mgm.yml
+++ b/.github/workflows/mgm.yml
@@ -1,241 +1,241 @@
 name: Freqtrade for MoniGoMany CI
 
-on:
-  push:
-    branches:
-      - develop
-    tags:
-      - mgm-v*
-  release:
-    types: [published]
-  pull_request:
-  schedule:
-    - cron:  '0 5 * * 4'
+# on:
+#   push:
+#     branches:
+#       - develop
+#     tags:
+#       - mgm-v*
+#   release:
+#     types: [published]
+#   pull_request:
+#   schedule:
+#     - cron:  '0 5 * * 4'
 
-jobs:
-  build_linux:
+# jobs:
+#   build_linux:
 
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ ubuntu-18.04, ubuntu-20.04 ]
-        python-version: [3.7, 3.8, 3.9]
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ ubuntu-18.04, ubuntu-20.04 ]
+#         python-version: [3.7, 3.8, 3.9]
 
-    steps:
-    - uses: actions/checkout@v2
+#     steps:
+#     - uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
+#     - name: Set up Python
+#       uses: actions/setup-python@v2
+#       with:
+#         python-version: ${{ matrix.python-version }}
 
-    - name: Cache_dependencies
-      uses: actions/cache@v2
-      id: cache
-      with:
-        path: ~/dependencies/
-        key: ${{ runner.os }}-dependencies
+#     - name: Cache_dependencies
+#       uses: actions/cache@v2
+#       id: cache
+#       with:
+#         path: ~/dependencies/
+#         key: ${{ runner.os }}-dependencies
 
-    - name: pip cache (linux)
-      uses: actions/cache@v2
-      if: startsWith(matrix.os, 'ubuntu')
-      with:
-        path: ~/.cache/pip
-        key: test-${{ matrix.os }}-${{ matrix.python-version }}-pip
+#     - name: pip cache (linux)
+#       uses: actions/cache@v2
+#       if: startsWith(matrix.os, 'ubuntu')
+#       with:
+#         path: ~/.cache/pip
+#         key: test-${{ matrix.os }}-${{ matrix.python-version }}-pip
 
-    - name: TA binary *nix
-      if: steps.cache.outputs.cache-hit != 'true'
-      run: |
-        cd build_helpers && ./install_ta-lib.sh ${HOME}/dependencies/; cd ..
+#     - name: TA binary *nix
+#       if: steps.cache.outputs.cache-hit != 'true'
+#       run: |
+#         cd build_helpers && ./install_ta-lib.sh ${HOME}/dependencies/; cd ..
 
-    - name: Installation - *nix
-      run: |
-        python -m pip install --upgrade pip
-        export LD_LIBRARY_PATH=${HOME}/dependencies/lib:$LD_LIBRARY_PATH
-        export TA_LIBRARY_PATH=${HOME}/dependencies/lib
-        export TA_INCLUDE_PATH=${HOME}/dependencies/include
-        pip install -r requirements-dev.txt
-        pip install -e .
+#     - name: Installation - *nix
+#       run: |
+#         python -m pip install --upgrade pip
+#         export LD_LIBRARY_PATH=${HOME}/dependencies/lib:$LD_LIBRARY_PATH
+#         export TA_LIBRARY_PATH=${HOME}/dependencies/lib
+#         export TA_INCLUDE_PATH=${HOME}/dependencies/include
+#         pip install -r requirements-dev.txt
+#         pip install -e .
 
-    - name: Tests
-      run: |
-        pytest --random-order --cov=freqtrade --cov-config=.coveragerc
-      if: matrix.python-version != '3.9'
+#     - name: Tests
+#       run: |
+#         pytest --random-order --cov=freqtrade --cov-config=.coveragerc
+#       if: matrix.python-version != '3.9'
 
-    - name: Tests incl. ccxt compatibility tests
-      run: |
-        pytest --random-order --cov=freqtrade --cov-config=.coveragerc --longrun
-      if: matrix.python-version == '3.9'
+#     - name: Tests incl. ccxt compatibility tests
+#       run: |
+#         pytest --random-order --cov=freqtrade --cov-config=.coveragerc --longrun
+#       if: matrix.python-version == '3.9'
 
-    - name: Coveralls
-      if: (startsWith(matrix.os, 'ubuntu-20') && matrix.python-version == '3.8')
-#       env:
-#         # Coveralls token. Not used as secret due to github not providing secrets to forked repositories
-#         COVERALLS_REPO_TOKEN: 6D1m0xupS3FgutfuGao8keFf9Hc0FpIXu
-      run: |
-        # Allow failure for coveralls
-        coveralls || true
+#     - name: Coveralls
+#       if: (startsWith(matrix.os, 'ubuntu-20') && matrix.python-version == '3.8')
+# #       env:
+# #         # Coveralls token. Not used as secret due to github not providing secrets to forked repositories
+# #         COVERALLS_REPO_TOKEN: 6D1m0xupS3FgutfuGao8keFf9Hc0FpIXu
+#       run: |
+#         # Allow failure for coveralls
+#         coveralls || true
 
-    - name: Backtesting
-      run: |
-        cp config_examples/config_bittrex.example.json config.json
-        freqtrade create-userdir --userdir user_data
-        freqtrade backtesting --datadir tests/testdata --strategy SampleStrategy
+#     - name: Backtesting
+#       run: |
+#         cp config_examples/config_bittrex.example.json config.json
+#         freqtrade create-userdir --userdir user_data
+#         freqtrade backtesting --datadir tests/testdata --strategy SampleStrategy
 
-    - name: Hyperopt
-      run: |
-        cp config_examples/config_bittrex.example.json config.json
-        freqtrade create-userdir --userdir user_data
-        freqtrade hyperopt --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
+#     - name: Hyperopt
+#       run: |
+#         cp config_examples/config_bittrex.example.json config.json
+#         freqtrade create-userdir --userdir user_data
+#         freqtrade hyperopt --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
 
-    - name: Flake8
-      run: |
-        flake8
+#     - name: Flake8
+#       run: |
+#         flake8
 
-    - name: Sort imports (isort)
-      run: |
-        isort --check .
+#     - name: Sort imports (isort)
+#       run: |
+#         isort --check .
 
-    - name: Mypy
-      run: |
-        mypy freqtrade scripts
+#     - name: Mypy
+#       run: |
+#         mypy freqtrade scripts
 
-  build_macos:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ macos-latest ]
-        python-version: [3.7, 3.8, 3.9]
+#   build_macos:
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ macos-latest ]
+#         python-version: [3.7, 3.8, 3.9]
 
-    steps:
-    - uses: actions/checkout@v2
+#     steps:
+#     - uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
+#     - name: Set up Python
+#       uses: actions/setup-python@v2
+#       with:
+#         python-version: ${{ matrix.python-version }}
 
-    - name: Cache_dependencies
-      uses: actions/cache@v2
-      id: cache
-      with:
-        path: ~/dependencies/
-        key: ${{ runner.os }}-dependencies
+#     - name: Cache_dependencies
+#       uses: actions/cache@v2
+#       id: cache
+#       with:
+#         path: ~/dependencies/
+#         key: ${{ runner.os }}-dependencies
 
-    - name: pip cache (macOS)
-      uses: actions/cache@v2
-      if: startsWith(matrix.os, 'macOS')
-      with:
-        path: ~/Library/Caches/pip
-        key: test-${{ matrix.os }}-${{ matrix.python-version }}-pip
+#     - name: pip cache (macOS)
+#       uses: actions/cache@v2
+#       if: startsWith(matrix.os, 'macOS')
+#       with:
+#         path: ~/Library/Caches/pip
+#         key: test-${{ matrix.os }}-${{ matrix.python-version }}-pip
 
-    - name: TA binary *nix
-      if: steps.cache.outputs.cache-hit != 'true'
-      run: |
-        cd build_helpers && ./install_ta-lib.sh ${HOME}/dependencies/; cd ..
+#     - name: TA binary *nix
+#       if: steps.cache.outputs.cache-hit != 'true'
+#       run: |
+#         cd build_helpers && ./install_ta-lib.sh ${HOME}/dependencies/; cd ..
 
-    - name: Installation - macOS
-      run: |
-        brew update
-        brew install hdf5 c-blosc
-        python -m pip install --upgrade pip
-        export LD_LIBRARY_PATH=${HOME}/dependencies/lib:$LD_LIBRARY_PATH
-        export TA_LIBRARY_PATH=${HOME}/dependencies/lib
-        export TA_INCLUDE_PATH=${HOME}/dependencies/include
-        pip install -r requirements-dev.txt
-        pip install -e .
+#     - name: Installation - macOS
+#       run: |
+#         brew update
+#         brew install hdf5 c-blosc
+#         python -m pip install --upgrade pip
+#         export LD_LIBRARY_PATH=${HOME}/dependencies/lib:$LD_LIBRARY_PATH
+#         export TA_LIBRARY_PATH=${HOME}/dependencies/lib
+#         export TA_INCLUDE_PATH=${HOME}/dependencies/include
+#         pip install -r requirements-dev.txt
+#         pip install -e .
 
-    - name: Tests
-      run: |
-        pytest --random-order --cov=freqtrade --cov-config=.coveragerc
+#     - name: Tests
+#       run: |
+#         pytest --random-order --cov=freqtrade --cov-config=.coveragerc
 
-    - name: Coveralls
-      if: (startsWith(matrix.os, 'ubuntu-20') && matrix.python-version == '3.8')
-#       env:
-#         # Coveralls token. Not used as secret due to github not providing secrets to forked repositories
-#         COVERALLS_REPO_TOKEN: 6D1m0xupS3FgutfuGao8keFf9Hc0FpIXu
-      run: |
-        # Allow failure for coveralls
-        coveralls -v  || true
+#     - name: Coveralls
+#       if: (startsWith(matrix.os, 'ubuntu-20') && matrix.python-version == '3.8')
+# #       env:
+# #         # Coveralls token. Not used as secret due to github not providing secrets to forked repositories
+# #         COVERALLS_REPO_TOKEN: 6D1m0xupS3FgutfuGao8keFf9Hc0FpIXu
+#       run: |
+#         # Allow failure for coveralls
+#         coveralls -v  || true
 
-    - name: Backtesting
-      run: |
-        cp config_examples/config_bittrex.example.json config.json
-        freqtrade create-userdir --userdir user_data
-        freqtrade backtesting --datadir tests/testdata --strategy SampleStrategy
+#     - name: Backtesting
+#       run: |
+#         cp config_examples/config_bittrex.example.json config.json
+#         freqtrade create-userdir --userdir user_data
+#         freqtrade backtesting --datadir tests/testdata --strategy SampleStrategy
 
-    - name: Hyperopt
-      run: |
-        cp config_examples/config_bittrex.example.json config.json
-        freqtrade create-userdir --userdir user_data
-        freqtrade hyperopt --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
+#     - name: Hyperopt
+#       run: |
+#         cp config_examples/config_bittrex.example.json config.json
+#         freqtrade create-userdir --userdir user_data
+#         freqtrade hyperopt --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
 
-    - name: Flake8
-      run: |
-        flake8
+#     - name: Flake8
+#       run: |
+#         flake8
 
-    - name: Sort imports (isort)
-      run: |
-        isort --check .
+#     - name: Sort imports (isort)
+#       run: |
+#         isort --check .
 
-    - name: Mypy
-      run: |
-        mypy freqtrade scripts
+#     - name: Mypy
+#       run: |
+#         mypy freqtrade scripts
 
 
-  build_windows:
+#   build_windows:
 
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ windows-latest ]
-        python-version: [3.7, 3.8]
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ windows-latest ]
+#         python-version: [3.7, 3.8]
 
-    steps:
-    - uses: actions/checkout@v2
+#     steps:
+#     - uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
+#     - name: Set up Python
+#       uses: actions/setup-python@v2
+#       with:
+#         python-version: ${{ matrix.python-version }}
 
-    - name: Pip cache (Windows)
-      uses: actions/cache@preview
-      if: startsWith(runner.os, 'Windows')
-      with:
-        path: ~\AppData\Local\pip\Cache
-        key: ${{ matrix.os }}-${{ matrix.python-version }}-pip
+#     - name: Pip cache (Windows)
+#       uses: actions/cache@preview
+#       if: startsWith(runner.os, 'Windows')
+#       with:
+#         path: ~\AppData\Local\pip\Cache
+#         key: ${{ matrix.os }}-${{ matrix.python-version }}-pip
 
-    - name: Installation
-      run: |
-        ./build_helpers/install_windows.ps1
+#     - name: Installation
+#       run: |
+#         ./build_helpers/install_windows.ps1
 
-    - name: Tests
-      run: |
-        pytest --random-order --cov=freqtrade --cov-config=.coveragerc
+#     - name: Tests
+#       run: |
+#         pytest --random-order --cov=freqtrade --cov-config=.coveragerc
 
-    - name: Backtesting
-      run: |
-        cp config_examples/config_bittrex.example.json config.json
-        freqtrade create-userdir --userdir user_data
-        freqtrade backtesting --datadir tests/testdata --strategy SampleStrategy
+#     - name: Backtesting
+#       run: |
+#         cp config_examples/config_bittrex.example.json config.json
+#         freqtrade create-userdir --userdir user_data
+#         freqtrade backtesting --datadir tests/testdata --strategy SampleStrategy
 
-    - name: Hyperopt
-      run: |
-        cp config_examples/config_bittrex.example.json config.json
-        freqtrade create-userdir --userdir user_data
-        freqtrade hyperopt --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
+#     - name: Hyperopt
+#       run: |
+#         cp config_examples/config_bittrex.example.json config.json
+#         freqtrade create-userdir --userdir user_data
+#         freqtrade hyperopt --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
 
-    - name: Flake8
-      run: |
-        flake8
+#     - name: Flake8
+#       run: |
+#         flake8
 
-    - name: Mypy
-      run: |
-        mypy freqtrade scripts
+#     - name: Mypy
+#       run: |
+#         mypy freqtrade scripts
 
   deploy:
-    needs: [ build_linux, build_macos, build_windows ]
+#     needs: [ build_linux, build_macos, build_windows ]
     runs-on: ubuntu-20.04
 
     if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'release') && github.repository == 'taina0407/freqtrade'
